name: Notificacion NTFY

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Ejecutar Hola Mundo
        run: node index.js

      - name: Enviar notificacion a ntfy
        run: |
          curl -X POST https://ntfy.sh/devops-itla \
          -H "Title: Nuevo Push en Main" \
          -H "Priority: 5" \
          -d "Se ha realizado un push a la rama main en el repositorio ${{ github.repository }} por ${{ github.actor }}"
